# Generated by Django 5.1.1 on 2024-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0002_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
