# Generated by Django 5.1.1 on 2024-11-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
